[application]

# App (Project) Name
name = "rustfs-gui"

# The static resource path
asset_dir = "public"

[web.app]

# HTML title tag content
title = "rustfs-gui"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.rustfs.cli.gui"

publisher = "RustFsGUI"

category = "Utility"

copyright = "Copyright 2025 rustfs.com"

icon = [
    "assets/icons/icon.icns",
    "assets/icons/icon.ico",
    "assets/icons/icon.png",
    "assets/icons/rustfs-icon.png",
]
#[bundle.macos]
#provider_short_name = "RustFs"
[bundle.windows]
tsp = true
icon_path = "assets/icons/icon.ico"
allow_downgrades = true
[bundle.windows.webview_install_mode]
[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = true