# Copyright 2024 RustFS Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  node0:
    image: rustfs:v1  # 替换为你的镜像名称和标签
    container_name: node0
    hostname: node0
    environment:
      - RUSTFS_VOLUMES=http://node{0...3}:9000/data/rustfs{0...3}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9000:9000"  # 映射宿主机的 9001 端口到容器的 9000 端口
      - "8000:9001"  # 映射宿主机的 9001 端口到容器的 9000 端口
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/rustfs:/app/rustfs
      # - ./data/node0:/data  # 将当前路径挂载到容器内的 /root/data
    command: "/app/rustfs"

  node1:
    image: rustfs:v1
    container_name: node1
    hostname: node1
    environment:
      - RUSTFS_VOLUMES=http://node{0...3}:9000/data/rustfs{0...3}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9001:9000"  # 映射宿主机的 9002 端口到容器的 9000 端口
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/rustfs:/app/rustfs 
      # - ./data/node1:/data
    command: "/app/rustfs"

  node2:
    image: rustfs:v1
    container_name: node2
    hostname: node2
    environment:
      - RUSTFS_VOLUMES=http://node{0...3}:9000/data/rustfs{0...3}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9002:9000"  # 映射宿主机的 9003 端口到容器的 9000 端口
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/rustfs:/app/rustfs
      # - ./data/node2:/data
    command: "/app/rustfs"

  node3:
    image: rustfs:v1
    container_name: node3
    hostname: node3
    environment:
      - RUSTFS_VOLUMES=http://node{0...3}:9000/data/rustfs{0...3}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9003:9000"  # 映射宿主机的 9004 端口到容器的 9000 端口
    volumes:
      - ./target/x86_64-unknown-linux-musl/release/rustfs:/app/rustfs
      # - ./data/node3:/data
    command: "/app/rustfs"
