version: '3.8'

services:
  node1:
    image: rustfs:v1  # 替换为你的镜像名称和标签
    container_name: node1
    environment:
      - RUSTFS_VOLUMES=http://node{1...4}:9000/root/data/target/volume/test{1...4}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9001:9000"  # 映射宿主机的 9001 端口到容器的 9000 端口
    volumes:
      - ..:/root/data  # 将当前路径挂载到容器内的 /root/data
    command: "/root/rustfs"
    networks:
      - my_network

  node2:
    image: rustfs:v1
    container_name: node2
    environment:
      - RUSTFS_VOLUMES=http://node{1...4}:9000/root/data/target/volume/test{1...4}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9002:9000"  # 映射宿主机的 9002 端口到容器的 9000 端口
    volumes:
      - ..:/root/data
    command: "mkdir -p /root/data/target/volume/test{1..4} && /root/data/target/ubuntu22.04/release/rustfs"
    networks:
      - my_network

  node3:
    image: rustfs:v1
    container_name: node3
    environment:
      - RUSTFS_VOLUMES=http://node{1...4}:9000/root/data/target/volume/test{1...4}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9003:9000"  # 映射宿主机的 9003 端口到容器的 9000 端口
    volumes:
      - ..:/root/data
    command: "mkdir -p /root/data/target/volume/test{1..4} && /root/data/target/ubuntu22.04/release/rustfs"
    networks:
      - my_network

  node4:
    image: rustfs:v1
    container_name: node4
    environment:
      - RUSTFS_VOLUMES=http://node{1...4}:9000/root/data/target/volume/test{1...4}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9002
    platform: linux/amd64
    ports:
      - "9004:9000"  # 映射宿主机的 9004 端口到容器的 9000 端口
    volumes:
      - ..:/root/data
    command: "mkdir -p /root/data/target/volume/test{1..4} && /root/data/target/ubuntu22.04/release/rustfs"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge