use std::fmt::Display;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Name {
    ObjectAccessedGet = 1,
    ObjectAccessedGetRetention,
    ObjectAccessedGetLegalHold,
    ObjectAccessedHead,
    ObjectAccessedAttributes,
    ObjectCreatedCompleteMultipartUpload,
    ObjectCreatedCopy,
    ObjectCreatedPost,
    ObjectCreatedPut,
    ObjectCreatedPutRetention,
    ObjectCreatedPutLegalHold,
    ObjectCreatedPutTagging,
    ObjectCreatedDeleteTagging,
    ObjectRemovedDelete,
    ObjectRemovedDeleteMarkerCreated,
    ObjectRemovedDeleteAllVersions,
    ObjectRemovedNoOP,
    BucketCreated,
    BucketRemoved,
    ObjectReplicationFailed,
    ObjectReplicationComplete,
    ObjectReplicationMissedThreshold,
    ObjectReplicationReplicatedAfterThreshold,
    ObjectReplicationNotTracked,
    ObjectRestorePost,
    ObjectRestoreCompleted,
    ObjectTransitionFailed,
    ObjectTransitionComplete,
    ObjectManyVersions,
    ObjectLargeVersions,
    PrefixManyFolders,
    ILMDelMarkerExpirationDelete,
    ObjectAccessedAll,
    ObjectCreatedAll,
    ObjectRemovedAll,
    ObjectReplicationAll,
    ObjectRestoreAll,
    ObjectTransitionAll,
    ObjectScannerAll,
    Everything,
}

impl Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match *self {
                Name::ObjectAccessedGet => "s3:ObjectAccessed:Get",
                Name::ObjectAccessedGetRetention => "s3:ObjectAccessed:GetRetention",
                Name::ObjectAccessedGetLegalHold => "s3:ObjectAccessed:GetLegalHold",
                Name::ObjectAccessedHead => "s3:ObjectAccessed:Head",
                Name::ObjectAccessedAttributes => "s3:ObjectAccessed:Attributes",
                Name::ObjectCreatedCompleteMultipartUpload => "s3:ObjectCreated:CompleteMultipartUpload",
                Name::ObjectCreatedCopy => "s3:ObjectCreated:Copy",
                Name::ObjectCreatedPost => "s3:ObjectCreated:Post",
                Name::ObjectCreatedPut => "s3:ObjectCreated:Put",
                Name::ObjectCreatedPutRetention => "s3:ObjectCreated:PutRetention",
                Name::ObjectCreatedPutLegalHold => "s3:ObjectCreated:PutLegalHold",
                Name::ObjectCreatedPutTagging => "s3:ObjectCreated:PutTagging",
                Name::ObjectCreatedDeleteTagging => "s3:ObjectCreated:DeleteTagging",
                Name::ObjectRemovedDelete => "s3:ObjectRemoved:Delete",
                Name::ObjectRemovedDeleteMarkerCreated => "s3:ObjectRemoved:DeleteMarkerCreated",
                Name::ObjectRemovedDeleteAllVersions => "s3:ObjectRemoved:DeleteAllVersions",
                Name::ObjectRemovedNoOP => "s3:ObjectRemoved:NoOP",
                Name::BucketCreated => "s3:BucketCreated:*",
                Name::BucketRemoved => "s3:BucketRemoved:*",
                Name::ObjectReplicationFailed => "s3:Replication:OperationFailedReplication",
                Name::ObjectReplicationComplete => "s3:Replication:OperationCompletedReplication",
                Name::ObjectReplicationMissedThreshold => "s3:Replication:OperationMissedThreshold",
                Name::ObjectReplicationReplicatedAfterThreshold => "s3:Replication:OperationReplicatedAfterThreshold",
                Name::ObjectReplicationNotTracked => "s3:Replication:OperationNotTracked",
                Name::ObjectRestorePost => "s3:ObjectRestore:Post",
                Name::ObjectRestoreCompleted => "s3:ObjectRestore:Completed",
                Name::ObjectTransitionFailed => "s3:ObjectTransition:Failed",
                Name::ObjectTransitionComplete => "s3:ObjectTransition:Complete",
                Name::ObjectManyVersions => "s3:Scanner:ManyVersions",
                Name::ObjectLargeVersions => "s3:Scanner:LargeVersions",
                Name::PrefixManyFolders => "s3:Scanner:BigPrefix",
                Name::ILMDelMarkerExpirationDelete => "s3:LifecycleDelMarkerExpiration:Delete",
                Name::ObjectAccessedAll => "s3:ObjectAccessed:*",
                Name::ObjectCreatedAll => "s3:ObjectCreated:*",
                Name::ObjectRemovedAll => "s3:ObjectRemoved:*",
                Name::ObjectReplicationAll => "s3:Replication:*",
                Name::ObjectRestoreAll => "s3:ObjectRestore:*",
                Name::ObjectTransitionAll => "s3:ObjectTransition:*",
                Name::ObjectScannerAll => "s3:Scanner:*",
                Name::Everything => "*",
            }
        )
    }
}
