services:
  node1:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=96
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=524288
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=16
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=32
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=24
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=33554432
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=50331648
      - RUSTFS_RUNTIME_WORKER_THREADS=24
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1536
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=600
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=80

  node2:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=96
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=524288
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=16
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=32
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=24
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=33554432
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=50331648
      - RUSTFS_RUNTIME_WORKER_THREADS=24
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1536
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=600
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=80

  node3:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=96
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=524288
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=16
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=32
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=24
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=33554432
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=50331648
      - RUSTFS_RUNTIME_WORKER_THREADS=24
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1536
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=600
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=80

  node4:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=96
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=524288
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=16
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=32
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=24
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=33554432
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=50331648
      - RUSTFS_RUNTIME_WORKER_THREADS=24
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1536
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=600
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=80
