services:
  node1:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=64
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=262144
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=12
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=24
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=16
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=16777216
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=33554432
      - RUSTFS_RUNTIME_WORKER_THREADS=20
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1024
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=300
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=60

  node2:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=64
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=262144
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=12
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=24
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=16
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=16777216
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=33554432
      - RUSTFS_RUNTIME_WORKER_THREADS=20
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1024
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=300
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=60

  node3:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=64
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=262144
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=12
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=24
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=16
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=16777216
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=33554432
      - RUSTFS_RUNTIME_WORKER_THREADS=20
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1024
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=300
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=60

  node4:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=64
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=262144
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=12
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=24
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=16
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=16777216
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=33554432
      - RUSTFS_RUNTIME_WORKER_THREADS=20
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=1024
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=300
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=60
