services:
  node1:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=56
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=131072
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=10
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=20
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=10
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=8388608
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=25165824
      - RUSTFS_RUNTIME_WORKER_THREADS=16
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=768
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=420
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=50

  node2:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=56
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=131072
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=10
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=20
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=10
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=8388608
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=25165824
      - RUSTFS_RUNTIME_WORKER_THREADS=16
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=768
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=420
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=50

  node3:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=56
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=131072
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=10
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=20
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=10
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=8388608
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=25165824
      - RUSTFS_RUNTIME_WORKER_THREADS=16
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=768
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=420
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=50

  node4:
    environment:
      - RUSTFS_OBJECT_MAX_CONCURRENT_DISK_READS=56
      - RUSTFS_OBJECT_IO_BUFFER_SIZE=131072
      - RUSTFS_OBJECT_MEDIUM_CONCURRENCY_THRESHOLD=10
      - RUSTFS_OBJECT_HIGH_CONCURRENCY_THRESHOLD=20
      - RUSTFS_OBJECT_IO_RANDOM_READAHEAD_DISABLE_CONCURRENCY=10
      - RUSTFS_OBJECT_DUPLEX_BUFFER_SIZE=8388608
      - RUSTFS_ERASURE_ENCODE_MAX_INFLIGHT_BYTES=25165824
      - RUSTFS_RUNTIME_WORKER_THREADS=16
      - RUSTFS_RUNTIME_MAX_BLOCKING_THREADS=768
      - RUSTFS_CAPACITY_SCHEDULED_INTERVAL=420
      - RUSTFS_CAPACITY_WRITE_FREQUENCY_THRESHOLD=50
