# config.toml
store_path = "/var/log/event-notifier"
channel_capacity = 5000

[[adapters]]
type = "Webhook"
endpoint = "http://127.0.0.1:3000/webhook"
auth_token = "your-auth-token"
max_retries = 3
timeout = 50

[adapters.custom_headers]
custom_server = "value_server"
custom_client = "value_client"

[[adapters]]
type = "Kafka"
brokers = "localhost:9092"
topic = "notifications"
max_retries = 3
timeout = 60

[[adapters]]
type = "Mqtt"
broker = "mqtt.example.com"
port = 1883
client_id = "event-notifier"
topic = "events"
max_retries = 3