{{- if .Values.mtls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rustfs.fullname" . }}-client-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "rustfs.fullname" . }}-client-tls
  {{- if .Values.mtls.existingIssuerRef.enabled }}
  issuerRef:
    name: {{ .Values.mtls.existingIssuerRef.name }}
    kind: {{ .Values.mtls.existingIssuerRef.kind }}
    group: {{ .Values.mtls.existingIssuerRef.group }}
  {{- else }}
  issuerRef:
    name: {{ include "rustfs.fullname" . }}-ca-issuer
    kind: Issuer
  {{- end }}
  commonName: {{ include "rustfs.fullname" . }}-cluster
  usages:
    - client auth
{{- end }}

