// Copyright 2024 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Consent-bound local drive performance measurement and offline export.
//!
//! The benchmark writes generated bytes to a task-owned scratch directory,
//! reads and verifies them, and removes the scratch state before returning.
//! The read follows the write and therefore measures the filesystem's warm
//! page-cache-visible path. It is not reported as cold physical-media I/O;
//! RustFS does not expose a portable cache-bypass adapter for this producer.
//! Existing StorageInfo counters are deliberately not used because passive
//! observations are not evidence of an active read/write benchmark.

use std::fs::{self, File, OpenOptions};
use std::io::{Cursor, Write as _};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use base64_simd::URL_SAFE_NO_PAD;
use p256::ecdsa::{Signature, SigningKey, signature::Signer as _};
use p256::pkcs8::DecodePrivateKey as _;
use serde::Serialize;
use sha2::{Digest as _, Sha256};
use thiserror::Error;
use time::{OffsetDateTime, format_description::well_known::Rfc3339};
use tokio::io::{AsyncReadExt as _, AsyncSeekExt as _, AsyncWriteExt as _};
use tokio_util::sync::CancellationToken;
use uuid::{Uuid, Variant, Version};
use zip::{CompressionMethod, ZipWriter, write::SimpleFileOptions};

use crate::connect::DeviceIdentity;

pub const DRIVE_SCHEMA_VERSION: u16 = 1;
pub const DRIVE_TOOL_ID: &str = "performance.drive";
pub const DRIVE_CAPABILITY: &str = "performance.drive@1";
pub const MAX_DRIVE_DURATION: Duration = Duration::from_secs(30);
pub const MAX_TEMPORARY_BYTES: u64 = 2_097_152;
pub const MAX_IO_BYTES: u64 = 1_048_576;
pub const MAX_BANDWIDTH_BYTES_PER_SECOND: u64 = 1_048_576;
pub const MAX_OPERATIONS: u64 = 1_024;
pub const MAX_BLOCK_BYTES: u64 = 65_536;
pub const MAX_RESULT_BYTES: usize = 262_144;
pub const MAX_ENVELOPE_BYTES: usize = 16_384;
pub const MAX_ARCHIVE_BYTES: usize = 524_288;
pub const MAX_DECOMPRESSED_BYTES: usize = 278_528;

const MAX_SAFE_INTEGER: u64 = 9_007_199_254_740_991;
const MAX_BUILD_FEATURES: usize = 64;
const MAX_VALIDITY_SECONDS: i64 = 2_592_000;
const MAX_FUTURE_SKEW_SECONDS: i64 = 300;
const SIGNATURE_DOMAIN: &[u8] = b"rustfs-diagnostic-envelope-v1\0";
const ENVELOPE_PATH: &str = "envelope.json";
const SIGNATURE_PATH: &str = "envelope.sig";
const RESULT_PATH: &str = "result.json";
const OUTPUT_MODE: u32 = 0o600;
const SCRATCH_MODE: u32 = 0o700;
const SCRATCH_PREFIX: &str = ".rustfs-connect-drive-";

static DRIVE_COLLECTOR_ACTIVE: AtomicBool = AtomicBool::new(false);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DriveOutcome {
    Succeeded,
    Failed,
    Cancelled,
}

impl DriveOutcome {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "SUCCEEDED",
            Self::Failed => "FAILED",
            Self::Cancelled => "CANCELLED",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DriveReasonCode {
    Complete,
    LimitExceeded,
    SourceUnavailable,
    PermissionDenied,
    Cancelled,
    CollectionFailed,
}

impl DriveReasonCode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Complete => "COMPLETE",
            Self::LimitExceeded => "LIMIT_EXCEEDED",
            Self::SourceUnavailable => "SOURCE_UNAVAILABLE",
            Self::PermissionDenied => "PERMISSION_DENIED",
            Self::Cancelled => "CANCELLED",
            Self::CollectionFailed => "COLLECTION_FAILED",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DriveTargetReasonCode {
    Complete,
    LimitExceeded,
    SourceUnavailable,
    PermissionDenied,
    TimedOut,
    Cancelled,
    IoFailure,
    VerificationFailed,
    CleanupFailed,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DriveReadMode {
    WarmPageCache,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveTargetParameters {
    pub scratch_bytes: u64,
    pub block_bytes: u64,
    pub duration_millis: u64,
    pub concurrency: u8,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveTargetUnits {
    pub bytes: &'static str,
    pub duration: &'static str,
    pub latency: &'static str,
    pub io_count: &'static str,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveProvenance {
    repository: &'static str,
    source_commit: String,
    executable_sha256: String,
    rustfs_version: String,
    os_family: DriveOsFamily,
    architecture: DriveArchitecture,
    build_features: Vec<String>,
}

impl DriveProvenance {
    pub fn new(
        source_commit: impl Into<String>,
        executable_sha256: impl Into<String>,
        rustfs_version: impl Into<String>,
        build_features: Vec<String>,
    ) -> Self {
        Self {
            repository: "rustfs/rustfs",
            source_commit: source_commit.into(),
            executable_sha256: executable_sha256.into(),
            rustfs_version: rustfs_version.into(),
            os_family: DriveOsFamily::current(),
            architecture: DriveArchitecture::current(),
            build_features,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
enum DriveOsFamily {
    Linux,
    Darwin,
    Windows,
    Freebsd,
    Other,
}

impl DriveOsFamily {
    fn current() -> Self {
        match std::env::consts::OS {
            "linux" => Self::Linux,
            "macos" => Self::Darwin,
            "windows" => Self::Windows,
            "freebsd" => Self::Freebsd,
            _ => Self::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
enum DriveArchitecture {
    #[serde(rename = "x86_64")]
    X86_64,
    Aarch64,
    Other,
}

impl DriveArchitecture {
    fn current() -> Self {
        match std::env::consts::ARCH {
            "x86_64" => Self::X86_64,
            "aarch64" => Self::Aarch64,
            _ => Self::Other,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LocalDriveConsent {
    pub consent_uid: String,
    pub policy_revision: u64,
    pub expires_at_unix: i64,
    pub confirmed: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DrivePerformanceRequest {
    pub organization_name: String,
    pub cluster_name: String,
    pub device_name: String,
    pub run_uid: String,
    pub artifact_uid: String,
    pub schema_version: u16,
    pub capability: String,
    pub consent: LocalDriveConsent,
    pub produced_at_unix: i64,
    pub expires_at_unix: i64,
    pub nonce: [u8; 32],
    pub duration: Duration,
    pub target_alias: String,
    pub scratch_root: PathBuf,
    pub scratch_bytes: u64,
    pub block_bytes: u64,
    pub provenance: DriveProvenance,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DrivePerformanceData {
    pub read_bytes: u64,
    pub write_bytes: u64,
    pub io_count: u64,
    pub duration_millis: u64,
    pub error_count: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveCoverage {
    requested_units: u32,
    completed_units: u32,
    unit: &'static str,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveDiagnosticResult {
    schema_version: u16,
    run_uid: String,
    tool_id: &'static str,
    capability: &'static str,
    outcome: DriveOutcome,
    reason_code: DriveReasonCode,
    duration_millis: u64,
    provenance: DriveProvenance,
    coverage: DriveCoverage,
    data: Option<DrivePerformanceData>,
}

impl DriveDiagnosticResult {
    pub fn outcome(&self) -> DriveOutcome {
        self.outcome
    }

    pub fn reason_code(&self) -> DriveReasonCode {
        self.reason_code
    }

    pub fn data(&self) -> Option<&DrivePerformanceData> {
        self.data.as_ref()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DriveTargetResult {
    pub target_alias: String,
    pub outcome: DriveOutcome,
    pub reason_code: DriveTargetReasonCode,
    pub parameters: DriveTargetParameters,
    pub units: DriveTargetUnits,
    pub read_mode: Option<DriveReadMode>,
    pub read_bytes: u64,
    pub write_bytes: u64,
    pub io_count: u64,
    pub cached_read_latency_micros: Option<u64>,
    pub write_latency_micros: Option<u64>,
    pub duration_millis: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DriveMeasurement {
    pub result: DriveDiagnosticResult,
    pub target: DriveTargetResult,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SignedDriveExport {
    pub artifact_uid: String,
    pub outcome: DriveOutcome,
    pub reason_code: DriveReasonCode,
    pub envelope_json: Vec<u8>,
    pub envelope_signature: Vec<u8>,
    pub result_json: Vec<u8>,
    pub archive_bytes: Vec<u8>,
    pub archive_sha256: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SavedDriveExport {
    pub artifact_uid: String,
    pub archive_size_bytes: u64,
    pub archive_sha256: String,
}

#[derive(Debug, Error)]
pub enum DrivePerformanceError {
    #[error("drive_performance_local_consent_required")]
    ConsentRequired,
    #[error("drive_performance_local_consent_expired")]
    ConsentExpired,
    #[error("drive_performance_request_expired")]
    Expired,
    #[error("drive_performance_invalid_request")]
    InvalidRequest,
    #[error("drive_performance_unsupported_version")]
    UnsupportedVersion,
    #[error("drive_performance_unsupported_capability")]
    UnsupportedCapability,
    #[error("drive_performance_limit_exceeded")]
    LimitExceeded,
    #[error("drive_performance_collection_cancelled")]
    Cancelled,
    #[error("drive_performance_collection_already_running")]
    Busy,
    #[error("drive_performance_export_signing_failed")]
    Signing,
    #[error("drive_performance_export_exists")]
    AlreadyExists,
    #[error("drive_performance_export_io_failed")]
    Io(#[source] std::io::Error),
    #[error("drive_performance_export_encoding_failed")]
    Encoding,
    #[error("drive_performance_export_durability_failed_after_commit")]
    DurabilityAfterCommit(#[source] std::io::Error),
}

pub async fn measure_drive(
    request: &DrivePerformanceRequest,
    cancel: &CancellationToken,
) -> Result<DriveMeasurement, DrivePerformanceError> {
    request.validate(unix_now()?)?;
    if cancel.is_cancelled() {
        return Ok(terminal_measurement(
            request,
            DriveOutcome::Cancelled,
            DriveReasonCode::Cancelled,
            DriveTargetReasonCode::Cancelled,
            0,
        ));
    }
    let _lease = CollectorLease::acquire()?;
    let started = Instant::now();
    let deadline = tokio::time::Instant::now() + request.duration;
    let mut scratch = match ScratchGuard::create(request) {
        Ok(scratch) => scratch,
        Err(error) => return Ok(failed_measurement(request, started.elapsed(), classify_io(&error), 0, 0, 0)),
    };

    let measured = run_benchmark(request, &scratch, cancel, deadline).await;
    let cleanup = scratch.cleanup();
    let elapsed = started.elapsed().min(request.duration);
    if cleanup.is_err() {
        let (read_bytes, write_bytes, io_count) = match &measured {
            Ok(sample) => (sample.read_bytes, sample.write_bytes, sample.io_count),
            Err(_) => (0, 0, 0),
        };
        return Ok(failed_measurement(
            request,
            elapsed,
            DriveTargetReasonCode::CleanupFailed,
            read_bytes,
            write_bytes,
            io_count,
        ));
    }
    match measured {
        Ok(sample) => Ok(success_measurement(request, elapsed, sample)),
        Err(BenchmarkFailure::Cancelled) => Ok(terminal_measurement(
            request,
            DriveOutcome::Cancelled,
            DriveReasonCode::Cancelled,
            DriveTargetReasonCode::Cancelled,
            elapsed_millis_allow_zero(elapsed),
        )),
        Err(BenchmarkFailure::TimedOut) => Ok(failed_measurement(request, elapsed, DriveTargetReasonCode::TimedOut, 0, 0, 0)),
        Err(BenchmarkFailure::Verification) => {
            Ok(failed_measurement(request, elapsed, DriveTargetReasonCode::VerificationFailed, 0, 0, 0))
        }
        Err(BenchmarkFailure::Io(error)) => Ok(failed_measurement(request, elapsed, classify_io(&error), 0, 0, 0)),
    }
}

pub fn sign_drive_export(
    request: &DrivePerformanceRequest,
    measurement: &DriveMeasurement,
    key: &DeviceIdentity,
    cancel: &CancellationToken,
) -> Result<SignedDriveExport, DrivePerformanceError> {
    request.validate(unix_now()?)?;
    check_cancel(cancel)?;
    let result = &measurement.result;
    if result.outcome != DriveOutcome::Succeeded
        || result.data.is_none()
        || result.run_uid != request.run_uid
        || result.schema_version != DRIVE_SCHEMA_VERSION
        || result.tool_id != DRIVE_TOOL_ID
        || result.capability != DRIVE_CAPABILITY
    {
        return Err(DrivePerformanceError::InvalidRequest);
    }
    let result_json = serde_json::to_vec(result).map_err(|_| DrivePerformanceError::Encoding)?;
    if result_json.is_empty() || result_json.len() > MAX_RESULT_BYTES {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    let device_key_id = hex_lower(&Sha256::digest(key.public_key_der()));
    let result_sha256 = hex_lower(&Sha256::digest(&result_json));
    let envelope = DriveEnvelope {
        format_version: "rustfs.connect.diagnosticEnvelope/1",
        protocol_version: "v1",
        organization_name: &request.organization_name,
        cluster_name: &request.cluster_name,
        device_name: &request.device_name,
        run_uid: &request.run_uid,
        artifact_uid: &request.artifact_uid,
        tool_id: DRIVE_TOOL_ID,
        schema_version: DRIVE_SCHEMA_VERSION,
        classification: "L1",
        consent_uid: &request.consent.consent_uid,
        policy_revision: request.consent.policy_revision,
        produced_at: timestamp(request.produced_at_unix)?,
        expires_at: timestamp(request.expires_at_unix)?,
        nonce: URL_SAFE_NO_PAD.encode_to_string(request.nonce),
        device_key_id: &device_key_id,
        payload: DrivePayload {
            path: RESULT_PATH,
            media_type: "application/json",
            size_bytes: result_json.len() as u64,
            sha256: &result_sha256,
        },
    };
    let envelope_json = serde_json::to_vec(&envelope).map_err(|_| DrivePerformanceError::Encoding)?;
    if envelope_json.is_empty() || envelope_json.len() > MAX_ENVELOPE_BYTES {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    let envelope_signature = signature_document(key, &device_key_id, &envelope_json)?;
    let decompressed = result_json
        .len()
        .checked_add(envelope_json.len())
        .and_then(|size| size.checked_add(envelope_signature.len()))
        .ok_or(DrivePerformanceError::LimitExceeded)?;
    if decompressed > MAX_DECOMPRESSED_BYTES {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    check_cancel(cancel)?;
    if unix_now()? >= request.expires_at_unix {
        return Err(DrivePerformanceError::Expired);
    }
    let archive_bytes = archive(&envelope_json, &envelope_signature, &result_json)?;
    if archive_bytes.len() > MAX_ARCHIVE_BYTES {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    let archive_sha256 = hex_lower(&Sha256::digest(&archive_bytes));
    Ok(SignedDriveExport {
        artifact_uid: request.artifact_uid.clone(),
        outcome: result.outcome,
        reason_code: result.reason_code,
        envelope_json,
        envelope_signature,
        result_json,
        archive_bytes,
        archive_sha256,
    })
}

pub fn save_signed_drive_export(
    output: &Path,
    export: &SignedDriveExport,
    cancel: &CancellationToken,
) -> Result<SavedDriveExport, DrivePerformanceError> {
    check_cancel(cancel)?;
    if !uuid7(&export.artifact_uid) {
        return Err(DrivePerformanceError::InvalidRequest);
    }
    if export.archive_bytes.is_empty() {
        return Err(DrivePerformanceError::InvalidRequest);
    }
    if export.archive_bytes.len() > MAX_ARCHIVE_BYTES {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    if hex_lower(&Sha256::digest(&export.archive_bytes)) != export.archive_sha256 {
        return Err(DrivePerformanceError::InvalidRequest);
    }
    let parent = output
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let filename = output
        .file_name()
        .ok_or(DrivePerformanceError::InvalidRequest)?
        .to_string_lossy();
    let temporary = parent.join(format!(".{filename}.{}.partial", export.artifact_uid));
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        options.mode(OUTPUT_MODE);
    }
    let mut file = options.open(&temporary).map_err(map_create_error)?;
    let saved = (|| {
        file.write_all(&export.archive_bytes).map_err(DrivePerformanceError::Io)?;
        check_cancel(cancel)?;
        file.sync_all().map_err(DrivePerformanceError::Io)?;
        check_cancel(cancel)?;
        fs::hard_link(&temporary, output).map_err(map_publish_error)?;
        fs::remove_file(&temporary).map_err(DrivePerformanceError::DurabilityAfterCommit)?;
        #[cfg(unix)]
        File::open(parent)
            .and_then(|directory| directory.sync_all())
            .map_err(DrivePerformanceError::DurabilityAfterCommit)?;
        Ok(SavedDriveExport {
            artifact_uid: export.artifact_uid.clone(),
            archive_size_bytes: export.archive_bytes.len() as u64,
            archive_sha256: export.archive_sha256.clone(),
        })
    })();
    if saved.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    saved
}

impl DrivePerformanceRequest {
    fn validate(&self, now_unix: i64) -> Result<(), DrivePerformanceError> {
        if self.schema_version != DRIVE_SCHEMA_VERSION {
            return Err(DrivePerformanceError::UnsupportedVersion);
        }
        if self.capability != DRIVE_CAPABILITY {
            return Err(DrivePerformanceError::UnsupportedCapability);
        }
        if !self.consent.confirmed || self.consent.policy_revision == 0 {
            return Err(DrivePerformanceError::ConsentRequired);
        }
        if self.consent.expires_at_unix <= now_unix || self.expires_at_unix > self.consent.expires_at_unix {
            return Err(DrivePerformanceError::ConsentExpired);
        }
        let validity = self
            .expires_at_unix
            .checked_sub(self.produced_at_unix)
            .ok_or(DrivePerformanceError::Expired)?;
        if self.produced_at_unix > now_unix.saturating_add(MAX_FUTURE_SKEW_SECONDS)
            || validity <= 0
            || validity > MAX_VALIDITY_SECONDS
            || self.expires_at_unix <= now_unix
        {
            return Err(DrivePerformanceError::Expired);
        }
        validate_drive_limits(self.duration, self.scratch_bytes, self.block_bytes)?;
        if !uuid7(&self.run_uid)
            || !uuid7(&self.artifact_uid)
            || !uuid7(&self.consent.consent_uid)
            || !resource_names_match(self)
            || self.target_alias != "drive-1"
            || self.scratch_root.as_os_str().is_empty()
            || !lower_hex(&self.provenance.source_commit, 40)
            || !lower_hex(&self.provenance.executable_sha256, 64)
            || !version(&self.provenance.rustfs_version)
            || self.provenance.build_features.len() > MAX_BUILD_FEATURES
            || !self.provenance.build_features.iter().all(|value| build_feature(value))
        {
            return Err(DrivePerformanceError::InvalidRequest);
        }
        Ok(())
    }
}

pub fn validate_drive_limits(duration: Duration, scratch_bytes: u64, block_bytes: u64) -> Result<(), DrivePerformanceError> {
    if duration.is_zero()
        || duration > MAX_DRIVE_DURATION
        || scratch_bytes == 0
        || scratch_bytes > MAX_TEMPORARY_BYTES
        || block_bytes == 0
        || block_bytes > MAX_BLOCK_BYTES
        || block_bytes > scratch_bytes
    {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    let io_bytes = scratch_bytes.checked_mul(2).ok_or(DrivePerformanceError::LimitExceeded)?;
    let blocks = scratch_bytes.div_ceil(block_bytes);
    let operations = blocks.checked_mul(2).ok_or(DrivePerformanceError::LimitExceeded)?;
    let bandwidth_budget = u64::try_from(
        u128::from(MAX_BANDWIDTH_BYTES_PER_SECOND)
            .checked_mul(duration.as_millis())
            .ok_or(DrivePerformanceError::LimitExceeded)?
            / 1_000,
    )
    .map_err(|_| DrivePerformanceError::LimitExceeded)?;
    if io_bytes > MAX_IO_BYTES || io_bytes > bandwidth_budget.max(1) || operations > MAX_OPERATIONS {
        return Err(DrivePerformanceError::LimitExceeded);
    }
    Ok(())
}

#[derive(Clone, Copy)]
struct BenchmarkSample {
    read_bytes: u64,
    write_bytes: u64,
    io_count: u64,
    read_latency: Duration,
    write_latency: Duration,
}

enum BenchmarkFailure {
    Cancelled,
    TimedOut,
    Verification,
    Io(std::io::Error),
}

async fn run_benchmark(
    request: &DrivePerformanceRequest,
    scratch: &ScratchGuard,
    cancel: &CancellationToken,
    deadline: tokio::time::Instant,
) -> Result<BenchmarkSample, BenchmarkFailure> {
    let std_file = scratch.open_file().map_err(BenchmarkFailure::Io)?;
    let mut file = tokio::fs::File::from_std(std_file);
    let block_size = usize::try_from(request.block_bytes).map_err(|_| BenchmarkFailure::Verification)?;
    let write_buffer = vec![0xa5; block_size];
    let mut remaining = request.scratch_bytes;
    let mut write_bytes = 0_u64;
    let mut io_count = 0_u64;
    let write_started = Instant::now();
    while remaining > 0 {
        let length = usize::try_from(remaining.min(request.block_bytes)).map_err(|_| BenchmarkFailure::Verification)?;
        cancellable(file.write_all(&write_buffer[..length]), cancel, deadline).await?;
        write_bytes = write_bytes.checked_add(length as u64).ok_or(BenchmarkFailure::Verification)?;
        io_count = io_count.checked_add(1).ok_or(BenchmarkFailure::Verification)?;
        remaining -= length as u64;
        tokio::task::yield_now().await;
    }
    cancellable(file.sync_all(), cancel, deadline).await?;
    let write_latency = write_started.elapsed();
    cancellable(file.seek(std::io::SeekFrom::Start(0)), cancel, deadline).await?;

    let mut read_buffer = vec![0_u8; block_size];
    remaining = request.scratch_bytes;
    let mut read_bytes = 0_u64;
    let read_started = Instant::now();
    while remaining > 0 {
        let length = usize::try_from(remaining.min(request.block_bytes)).map_err(|_| BenchmarkFailure::Verification)?;
        cancellable(file.read_exact(&mut read_buffer[..length]), cancel, deadline).await?;
        if read_buffer[..length] != write_buffer[..length] {
            return Err(BenchmarkFailure::Verification);
        }
        read_bytes = read_bytes.checked_add(length as u64).ok_or(BenchmarkFailure::Verification)?;
        io_count = io_count.checked_add(1).ok_or(BenchmarkFailure::Verification)?;
        remaining -= length as u64;
        tokio::task::yield_now().await;
    }
    let read_latency = read_started.elapsed();
    drop(file);
    if read_bytes != request.scratch_bytes || write_bytes != request.scratch_bytes || io_count > MAX_OPERATIONS {
        return Err(BenchmarkFailure::Verification);
    }
    Ok(BenchmarkSample {
        read_bytes,
        write_bytes,
        io_count,
        read_latency,
        write_latency,
    })
}

async fn cancellable<T, F>(
    operation: F,
    cancel: &CancellationToken,
    deadline: tokio::time::Instant,
) -> Result<T, BenchmarkFailure>
where
    F: std::future::Future<Output = std::io::Result<T>>,
{
    tokio::select! {
        () = cancel.cancelled() => Err(BenchmarkFailure::Cancelled),
        () = tokio::time::sleep_until(deadline) => Err(BenchmarkFailure::TimedOut),
        result = operation => result.map_err(BenchmarkFailure::Io),
    }
}

struct ScratchGuard {
    directory: PathBuf,
    file: PathBuf,
    active: bool,
}

impl ScratchGuard {
    fn create(request: &DrivePerformanceRequest) -> std::io::Result<Self> {
        let metadata = fs::symlink_metadata(&request.scratch_root)?;
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::NotADirectory,
                "drive benchmark scratch root must be a real directory",
            ));
        }
        let directory = request.scratch_root.join(format!("{SCRATCH_PREFIX}{}", request.artifact_uid));
        let mut builder = fs::DirBuilder::new();
        #[cfg(unix)]
        {
            use std::os::unix::fs::DirBuilderExt as _;
            builder.mode(SCRATCH_MODE);
        }
        builder.create(&directory)?;
        Ok(Self {
            file: directory.join("benchmark.bin"),
            directory,
            active: true,
        })
    }

    fn open_file(&self) -> std::io::Result<File> {
        let mut options = OpenOptions::new();
        options.read(true).write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt as _;
            options.mode(OUTPUT_MODE);
        }
        options.open(&self.file)
    }

    fn cleanup(&mut self) -> std::io::Result<()> {
        match fs::remove_file(&self.file) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
        fs::remove_dir(&self.directory)?;
        self.active = false;
        Ok(())
    }
}

impl Drop for ScratchGuard {
    fn drop(&mut self) {
        if self.active {
            let _ = fs::remove_file(&self.file);
            let _ = fs::remove_dir(&self.directory);
        }
    }
}

pub(crate) struct CollectorLease;

impl CollectorLease {
    pub(crate) fn acquire() -> Result<Self, DrivePerformanceError> {
        DRIVE_COLLECTOR_ACTIVE
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .map(|_| Self)
            .map_err(|_| DrivePerformanceError::Busy)
    }
}

impl Drop for CollectorLease {
    fn drop(&mut self) {
        DRIVE_COLLECTOR_ACTIVE.store(false, Ordering::Release);
    }
}

fn success_measurement(request: &DrivePerformanceRequest, elapsed: Duration, sample: BenchmarkSample) -> DriveMeasurement {
    let duration_millis = elapsed_millis(elapsed);
    let data = DrivePerformanceData {
        read_bytes: sample.read_bytes,
        write_bytes: sample.write_bytes,
        io_count: sample.io_count,
        duration_millis,
        error_count: 0,
    };
    DriveMeasurement {
        result: result(
            request,
            DriveOutcome::Succeeded,
            DriveReasonCode::Complete,
            duration_millis,
            1,
            Some(data),
        ),
        target: DriveTargetResult {
            target_alias: request.target_alias.clone(),
            outcome: DriveOutcome::Succeeded,
            reason_code: DriveTargetReasonCode::Complete,
            parameters: target_parameters(request),
            units: target_units(),
            read_mode: Some(DriveReadMode::WarmPageCache),
            read_bytes: sample.read_bytes,
            write_bytes: sample.write_bytes,
            io_count: sample.io_count,
            cached_read_latency_micros: Some(elapsed_micros(sample.read_latency)),
            write_latency_micros: Some(elapsed_micros(sample.write_latency)),
            duration_millis,
        },
    }
}

pub(crate) fn failed_measurement(
    request: &DrivePerformanceRequest,
    elapsed: Duration,
    target_reason: DriveTargetReasonCode,
    read_bytes: u64,
    write_bytes: u64,
    io_count: u64,
) -> DriveMeasurement {
    let reason = match target_reason {
        DriveTargetReasonCode::PermissionDenied => DriveReasonCode::PermissionDenied,
        DriveTargetReasonCode::SourceUnavailable => DriveReasonCode::SourceUnavailable,
        _ => DriveReasonCode::CollectionFailed,
    };
    let duration_millis = elapsed_millis_allow_zero(elapsed);
    DriveMeasurement {
        result: result(request, DriveOutcome::Failed, reason, duration_millis, 0, None),
        target: DriveTargetResult {
            target_alias: request.target_alias.clone(),
            outcome: DriveOutcome::Failed,
            reason_code: target_reason,
            parameters: target_parameters(request),
            units: target_units(),
            read_mode: None,
            read_bytes,
            write_bytes,
            io_count,
            cached_read_latency_micros: None,
            write_latency_micros: None,
            duration_millis,
        },
    }
}

fn terminal_measurement(
    request: &DrivePerformanceRequest,
    outcome: DriveOutcome,
    reason_code: DriveReasonCode,
    target_reason: DriveTargetReasonCode,
    duration_millis: u64,
) -> DriveMeasurement {
    DriveMeasurement {
        result: result(request, outcome, reason_code, duration_millis, 0, None),
        target: DriveTargetResult {
            target_alias: request.target_alias.clone(),
            outcome,
            reason_code: target_reason,
            parameters: target_parameters(request),
            units: target_units(),
            read_mode: None,
            read_bytes: 0,
            write_bytes: 0,
            io_count: 0,
            cached_read_latency_micros: None,
            write_latency_micros: None,
            duration_millis,
        },
    }
}

fn target_parameters(request: &DrivePerformanceRequest) -> DriveTargetParameters {
    DriveTargetParameters {
        scratch_bytes: request.scratch_bytes,
        block_bytes: request.block_bytes,
        duration_millis: elapsed_millis_allow_zero(request.duration),
        concurrency: 1,
    }
}

fn target_units() -> DriveTargetUnits {
    DriveTargetUnits {
        bytes: "BYTE",
        duration: "MILLISECOND",
        latency: "MICROSECOND",
        io_count: "OPERATION",
    }
}

fn result(
    request: &DrivePerformanceRequest,
    outcome: DriveOutcome,
    reason_code: DriveReasonCode,
    duration_millis: u64,
    completed_units: u32,
    data: Option<DrivePerformanceData>,
) -> DriveDiagnosticResult {
    DriveDiagnosticResult {
        schema_version: DRIVE_SCHEMA_VERSION,
        run_uid: request.run_uid.clone(),
        tool_id: DRIVE_TOOL_ID,
        capability: DRIVE_CAPABILITY,
        outcome,
        reason_code,
        duration_millis: duration_millis.min(30_000),
        provenance: request.provenance.clone(),
        coverage: DriveCoverage {
            requested_units: 1,
            completed_units,
            unit: "WINDOW",
        },
        data,
    }
}

pub(crate) fn classify_io(error: &std::io::Error) -> DriveTargetReasonCode {
    match error.kind() {
        std::io::ErrorKind::PermissionDenied | std::io::ErrorKind::ReadOnlyFilesystem => DriveTargetReasonCode::PermissionDenied,
        std::io::ErrorKind::StorageFull | std::io::ErrorKind::FileTooLarge | std::io::ErrorKind::QuotaExceeded => {
            DriveTargetReasonCode::LimitExceeded
        }
        std::io::ErrorKind::NotFound | std::io::ErrorKind::NotADirectory => DriveTargetReasonCode::SourceUnavailable,
        _ => DriveTargetReasonCode::IoFailure,
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DriveEnvelope<'a> {
    format_version: &'static str,
    protocol_version: &'static str,
    organization_name: &'a str,
    cluster_name: &'a str,
    device_name: &'a str,
    run_uid: &'a str,
    artifact_uid: &'a str,
    tool_id: &'static str,
    schema_version: u16,
    classification: &'static str,
    consent_uid: &'a str,
    policy_revision: u64,
    produced_at: String,
    expires_at: String,
    nonce: String,
    device_key_id: &'a str,
    payload: DrivePayload<'a>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DrivePayload<'a> {
    path: &'static str,
    media_type: &'static str,
    size_bytes: u64,
    sha256: &'a str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DriveSignature<'a> {
    algorithm: &'static str,
    key_id: &'a str,
    value: String,
}

fn signature_document(key: &DeviceIdentity, key_id: &str, envelope: &[u8]) -> Result<Vec<u8>, DrivePerformanceError> {
    let pkcs8 = key.to_pkcs8_der().map_err(|_| DrivePerformanceError::Signing)?;
    let signing_key = SigningKey::from_pkcs8_der(pkcs8.as_slice()).map_err(|_| DrivePerformanceError::Signing)?;
    let mut input = Vec::with_capacity(SIGNATURE_DOMAIN.len() + envelope.len());
    input.extend_from_slice(SIGNATURE_DOMAIN);
    input.extend_from_slice(envelope);
    let signature: Signature = signing_key.sign(&input);
    serde_json::to_vec(&DriveSignature {
        algorithm: "ES256",
        key_id,
        value: URL_SAFE_NO_PAD.encode_to_string(signature.normalize_s().to_bytes()),
    })
    .map_err(|_| DrivePerformanceError::Encoding)
}

fn archive(envelope: &[u8], signature: &[u8], result: &[u8]) -> Result<Vec<u8>, DrivePerformanceError> {
    let cursor = Cursor::new(Vec::with_capacity(envelope.len() + signature.len() + result.len() + 512));
    let mut writer = ZipWriter::new(cursor);
    let options = SimpleFileOptions::DEFAULT
        .compression_method(CompressionMethod::Stored)
        .unix_permissions(OUTPUT_MODE);
    for (name, bytes) in [(ENVELOPE_PATH, envelope), (SIGNATURE_PATH, signature), (RESULT_PATH, result)] {
        writer
            .start_file(name, options)
            .map_err(|_| DrivePerformanceError::Encoding)?;
        writer.write_all(bytes).map_err(DrivePerformanceError::Io)?;
    }
    writer
        .finish()
        .map(|cursor| cursor.into_inner())
        .map_err(|_| DrivePerformanceError::Encoding)
}

fn resource_names_match(request: &DrivePerformanceRequest) -> bool {
    let Some(organization_uid) = request.organization_name.strip_prefix("organizations/") else {
        return false;
    };
    if !uuid7(organization_uid) {
        return false;
    }
    let cluster_prefix = format!("{}/clusters/", request.organization_name);
    let Some(cluster_uid) = request.cluster_name.strip_prefix(&cluster_prefix) else {
        return false;
    };
    if !uuid7(cluster_uid) {
        return false;
    }
    let device_prefix = format!("{}/clusterDevices/", request.cluster_name);
    request.device_name.strip_prefix(&device_prefix).is_some_and(uuid7)
}

fn uuid7(value: &str) -> bool {
    Uuid::parse_str(value).is_ok_and(|uuid| {
        uuid.get_version() == Some(Version::SortRand) && uuid.get_variant() == Variant::RFC4122 && uuid.to_string() == value
    })
}

fn lower_hex(value: &str, length: usize) -> bool {
    value.len() == length
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn build_feature(value: &str) -> bool {
    value.len() <= 64
        && value.as_bytes().first().is_some_and(u8::is_ascii_lowercase)
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'_' | b'-'))
}

fn version(value: &str) -> bool {
    if value.is_empty()
        || value.len() > 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-'))
    {
        return false;
    }
    let (core, suffix) = value
        .split_once('-')
        .map_or((value, None), |(core, suffix)| (core, Some(suffix)));
    if suffix.is_some_and(str::is_empty) {
        return false;
    }
    let mut parts = core.split('.');
    parts.clone().count() == 3 && parts.all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
}

fn timestamp(unix: i64) -> Result<String, DrivePerformanceError> {
    OffsetDateTime::from_unix_timestamp(unix)
        .map_err(|_| DrivePerformanceError::InvalidRequest)?
        .format(&Rfc3339)
        .map_err(|_| DrivePerformanceError::InvalidRequest)
}

fn unix_now() -> Result<i64, DrivePerformanceError> {
    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| DrivePerformanceError::InvalidRequest)?;
    i64::try_from(duration.as_secs()).map_err(|_| DrivePerformanceError::InvalidRequest)
}

fn check_cancel(cancel: &CancellationToken) -> Result<(), DrivePerformanceError> {
    if cancel.is_cancelled() {
        Err(DrivePerformanceError::Cancelled)
    } else {
        Ok(())
    }
}

fn elapsed_millis(duration: Duration) -> u64 {
    elapsed_millis_allow_zero(duration).max(1)
}

fn elapsed_millis_allow_zero(duration: Duration) -> u64 {
    u64::try_from(duration.as_millis()).unwrap_or(u64::MAX).min(30_000)
}

fn elapsed_micros(duration: Duration) -> u64 {
    u64::try_from(duration.as_micros())
        .unwrap_or(MAX_SAFE_INTEGER)
        .min(MAX_SAFE_INTEGER)
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut value = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        use std::fmt::Write as _;
        write!(&mut value, "{byte:02x}").expect("writing hexadecimal to a string cannot fail");
    }
    value
}

fn map_create_error(error: std::io::Error) -> DrivePerformanceError {
    if error.kind() == std::io::ErrorKind::AlreadyExists {
        DrivePerformanceError::AlreadyExists
    } else {
        DrivePerformanceError::Io(error)
    }
}

fn map_publish_error(error: std::io::Error) -> DrivePerformanceError {
    if error.kind() == std::io::ErrorKind::AlreadyExists {
        DrivePerformanceError::AlreadyExists
    } else {
        DrivePerformanceError::Io(error)
    }
}
