// Copyright 2024 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Consent-bound client-to-deployment performance measurement.
//!
//! The producer sends generated bytes to, or reads generated bytes from, the
//! bounded RustFS admin speedtest endpoint. It never reads or writes customer
//! objects and keeps deployment credentials local to the invoking process.

use std::fs::{self, File, OpenOptions};
use std::future::Future;
use std::io::{Cursor, Read, Write as _};
use std::path::Path;
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use base64_simd::URL_SAFE_NO_PAD;
use bytes::Bytes;
use futures::StreamExt as _;
use p256::ecdsa::{Signature, SigningKey, signature::Signer as _};
use p256::pkcs8::DecodePrivateKey as _;
use reqwest::{Client, Method, Response, StatusCode, Url};
use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};
use thiserror::Error;
use time::{OffsetDateTime, format_description::well_known::Rfc3339};
use tokio_util::sync::CancellationToken;
use uuid::{Uuid, Variant, Version};
use zeroize::Zeroizing;
use zip::{CompressionMethod, ZipWriter, write::SimpleFileOptions};

use crate::connect::DeviceIdentity;

pub const CLIENT_SCHEMA_VERSION: u16 = 1;
pub const CLIENT_TOOL_ID: &str = "performance.client";
pub const CLIENT_CAPABILITY: &str = "performance.client@1";
pub const MAX_CLIENT_DURATION: Duration = Duration::from_secs(30);
pub const MAX_CLIENT_TRAFFIC_BYTES: u64 = 1_048_576;
pub const MAX_CLIENT_BANDWIDTH_BYTES_PER_SECOND: u64 = 1_048_576;
pub const MAX_CLIENT_RESULT_BYTES: usize = 262_144;

const MAX_SAFE_INTEGER: u64 = 9_007_199_254_740_991;
const MAX_BUILD_FEATURES: usize = 64;
const MAX_VALIDITY_SECONDS: i64 = 2_592_000;
const MAX_FUTURE_SKEW_SECONDS: i64 = 300;
const MAX_ENVELOPE_BYTES: usize = 16_384;
const MAX_ARCHIVE_BYTES: usize = 524_288;
const MAX_DECOMPRESSED_BYTES: usize = 278_528;
const SIGNATURE_DOMAIN: &[u8] = b"rustfs-diagnostic-envelope-v1\0";
const ENVELOPE_PATH: &str = "envelope.json";
const SIGNATURE_PATH: &str = "envelope.sig";
const RESULT_PATH: &str = "result.json";
const CLIENT_SPEEDTEST_PATH: &str = "/rustfs/admin/v3/speedtest/client/devnull";
const MAX_CLIENT_RESPONSE_BYTES: usize = 16_384;
const OUTPUT_MODE: u32 = 0o600;

static CLIENT_COLLECTOR_ACTIVE: AtomicBool = AtomicBool::new(false);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ClientOperation {
    GetObject,
    PutObject,
}

impl ClientOperation {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::GetObject => "GET_OBJECT",
            Self::PutObject => "PUT_OBJECT",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ClientOutcome {
    Succeeded,
    Failed,
    Cancelled,
}

impl ClientOutcome {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "SUCCEEDED",
            Self::Failed => "FAILED",
            Self::Cancelled => "CANCELLED",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ClientReasonCode {
    Complete,
    SourceUnavailable,
    PermissionDenied,
    Cancelled,
    CollectionFailed,
}

impl ClientReasonCode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Complete => "COMPLETE",
            Self::SourceUnavailable => "SOURCE_UNAVAILABLE",
            Self::PermissionDenied => "PERMISSION_DENIED",
            Self::Cancelled => "CANCELLED",
            Self::CollectionFailed => "COLLECTION_FAILED",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ClientTargetReasonCode {
    Complete,
    EndpointUnavailable,
    ProxyFailure,
    PermissionDenied,
    TimedOut,
    Cancelled,
    ProtocolFailure,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientTargetParameters {
    pub operation: ClientOperation,
    pub requested_bytes: u64,
    pub duration_millis: u64,
    pub concurrency: u8,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientTargetUnits {
    pub bytes: &'static str,
    pub duration: &'static str,
    pub latency: &'static str,
    pub operation_count: &'static str,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientProvenance {
    repository: &'static str,
    source_commit: String,
    executable_sha256: String,
    rustfs_version: String,
    os_family: ClientOsFamily,
    architecture: ClientArchitecture,
    build_features: Vec<String>,
}

impl ClientProvenance {
    pub fn new(
        source_commit: impl Into<String>,
        executable_sha256: impl Into<String>,
        rustfs_version: impl Into<String>,
        build_features: Vec<String>,
    ) -> Self {
        Self {
            repository: "rustfs/rustfs",
            source_commit: source_commit.into(),
            executable_sha256: executable_sha256.into(),
            rustfs_version: rustfs_version.into(),
            os_family: ClientOsFamily::current(),
            architecture: ClientArchitecture::current(),
            build_features,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
enum ClientOsFamily {
    Linux,
    Darwin,
    Windows,
    Freebsd,
    Other,
}

impl ClientOsFamily {
    fn current() -> Self {
        match std::env::consts::OS {
            "linux" => Self::Linux,
            "macos" => Self::Darwin,
            "windows" => Self::Windows,
            "freebsd" => Self::Freebsd,
            _ => Self::Other,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
enum ClientArchitecture {
    #[serde(rename = "x86_64")]
    X86_64,
    Aarch64,
    Other,
}

impl ClientArchitecture {
    fn current() -> Self {
        match std::env::consts::ARCH {
            "x86_64" => Self::X86_64,
            "aarch64" => Self::Aarch64,
            _ => Self::Other,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LocalClientConsent {
    pub consent_uid: String,
    pub policy_revision: u64,
    pub expires_at_unix: i64,
    pub confirmed: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClientPerformanceRequest {
    pub organization_name: String,
    pub cluster_name: String,
    pub device_name: String,
    pub run_uid: String,
    pub artifact_uid: String,
    pub schema_version: u16,
    pub capability: String,
    pub consent: LocalClientConsent,
    pub produced_at_unix: i64,
    pub expires_at_unix: i64,
    pub nonce: [u8; 32],
    pub duration: Duration,
    pub operation: ClientOperation,
    pub traffic_bytes: u64,
    pub target_alias: String,
    pub provenance: ClientProvenance,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientPerformanceData {
    pub operation: ClientOperation,
    pub transferred_bytes: u64,
    pub completed_operations: u64,
    pub duration_millis: u64,
    pub error_count: u64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
struct ClientCoverage {
    requested_units: u32,
    completed_units: u32,
    unit: &'static str,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientDiagnosticResult {
    schema_version: u16,
    run_uid: String,
    tool_id: &'static str,
    capability: &'static str,
    outcome: ClientOutcome,
    reason_code: ClientReasonCode,
    duration_millis: u64,
    provenance: ClientProvenance,
    coverage: ClientCoverage,
    data: Option<ClientPerformanceData>,
}

impl ClientDiagnosticResult {
    pub fn outcome(&self) -> ClientOutcome {
        self.outcome
    }

    pub fn reason_code(&self) -> ClientReasonCode {
        self.reason_code
    }

    pub fn data(&self) -> Option<&ClientPerformanceData> {
        self.data.as_ref()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientTargetResult {
    pub target_alias: String,
    pub outcome: ClientOutcome,
    pub reason_code: ClientTargetReasonCode,
    pub parameters: ClientTargetParameters,
    pub units: ClientTargetUnits,
    pub transferred_bytes: u64,
    pub completed_operations: u64,
    pub latency_micros: Option<u64>,
    pub duration_millis: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClientMeasurement {
    pub result: ClientDiagnosticResult,
    pub target: ClientTargetResult,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ClientProbeMeasurement {
    pub transferred_bytes: u64,
    pub duration: Duration,
    pub latency: Duration,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ClientProbeError {
    EndpointUnavailable,
    ProxyFailure,
    PermissionDenied,
    TimedOut,
    Cancelled,
    ProtocolFailure,
}

pub type ClientProbeFuture<'a> = Pin<Box<dyn Future<Output = Result<ClientProbeMeasurement, ClientProbeError>> + Send + 'a>>;

pub trait ClientProbe: Send + Sync {
    fn probe<'a>(&'a self, request: &'a ClientPerformanceRequest, cancel: &'a CancellationToken) -> ClientProbeFuture<'a>;
}

pub struct HttpClientProbe {
    endpoint: Url,
    client: Client,
    access_key: Zeroizing<String>,
    secret_key: Zeroizing<String>,
    session_token: Zeroizing<String>,
    proxy_configured: bool,
}

impl HttpClientProbe {
    pub fn new(
        endpoint: &str,
        root_ca_pem: Option<&[u8]>,
        proxy: Option<&str>,
        access_key: Zeroizing<String>,
        secret_key: Zeroizing<String>,
        session_token: Zeroizing<String>,
        timeout: Duration,
    ) -> Result<Self, ClientPerformanceError> {
        let endpoint = deployment_endpoint(endpoint)?;
        if access_key.is_empty() || secret_key.is_empty() {
            return Err(ClientPerformanceError::InvalidCredential);
        }
        let mut builder = Client::builder()
            .no_proxy()
            .redirect(reqwest::redirect::Policy::none())
            .timeout(timeout);
        if let Some(root_ca_pem) = root_ca_pem {
            let certificate =
                reqwest::Certificate::from_pem(root_ca_pem).map_err(|_| ClientPerformanceError::InvalidRootCertificate)?;
            builder = builder.add_root_certificate(certificate);
        }
        if let Some(proxy) = proxy {
            let proxy_url = proxy_url(proxy)?;
            builder = builder.proxy(reqwest::Proxy::all(proxy_url).map_err(|_| ClientPerformanceError::InvalidProxy)?);
        }
        let client = builder.build().map_err(|_| ClientPerformanceError::TransportConfiguration)?;
        Ok(Self {
            endpoint,
            client,
            access_key,
            secret_key,
            session_token,
            proxy_configured: proxy.is_some(),
        })
    }

    async fn execute(
        &self,
        request: &ClientPerformanceRequest,
        cancel: &CancellationToken,
    ) -> Result<ClientProbeMeasurement, ClientProbeError> {
        let started = Instant::now();
        let traffic_bytes = usize::try_from(request.traffic_bytes).map_err(|_| ClientProbeError::ProtocolFailure)?;
        let payload = match request.operation {
            ClientOperation::PutObject => Bytes::from(vec![0xa5; traffic_bytes]),
            ClientOperation::GetObject => Bytes::new(),
        };
        let mut url = self
            .endpoint
            .join(CLIENT_SPEEDTEST_PATH)
            .map_err(|_| ClientProbeError::ProtocolFailure)?;
        let method = match request.operation {
            ClientOperation::PutObject => Method::POST,
            ClientOperation::GetObject => {
                url.query_pairs_mut().append_pair("bytes", &request.traffic_bytes.to_string());
                Method::GET
            }
        };
        let payload_hash = hex_lower(&Sha256::digest(&payload));
        let unsigned = http::Request::builder()
            .method(method.clone())
            .uri(url.as_str())
            .header("x-amz-content-sha256", payload_hash)
            .body(())
            .map_err(|_| ClientProbeError::ProtocolFailure)?;
        let signed_headers = rustfs_signer::try_sign_v4_headers(
            unsigned.into_parts().0,
            i64::try_from(payload.len()).map_err(|_| ClientProbeError::ProtocolFailure)?,
            &self.access_key,
            &self.secret_key,
            &self.session_token,
            "us-east-1",
        )
        .map_err(|_| ClientProbeError::ProtocolFailure)?;
        let send = self.client.request(method, url).headers(signed_headers).body(payload).send();
        let response = tokio::select! {
            () = cancel.cancelled() => return Err(ClientProbeError::Cancelled),
            response = send => response.map_err(|error| self.transport_error(&error))?,
        };
        let status = response.status();
        if status == StatusCode::UNAUTHORIZED || status == StatusCode::FORBIDDEN {
            return Err(ClientProbeError::PermissionDenied);
        }
        if !status.is_success() {
            return Err(ClientProbeError::ProtocolFailure);
        }
        let transferred_bytes = match request.operation {
            ClientOperation::PutObject => {
                let body = self.read_response_body(response, MAX_CLIENT_RESPONSE_BYTES, cancel).await?;
                let response: ClientDevnullResponse =
                    serde_json::from_slice(&body).map_err(|_| ClientProbeError::ProtocolFailure)?;
                if !response.measured || response.kind != "client-devnull" || response.rx_bytes != request.traffic_bytes {
                    return Err(ClientProbeError::ProtocolFailure);
                }
                request.traffic_bytes
            }
            ClientOperation::GetObject => {
                let body = self.read_response_body(response, traffic_bytes, cancel).await?;
                let body_len = u64::try_from(body.len()).map_err(|_| ClientProbeError::ProtocolFailure)?;
                if body_len != request.traffic_bytes || body.iter().any(|byte| *byte != 0) {
                    return Err(ClientProbeError::ProtocolFailure);
                }
                body_len
            }
        };
        let latency = started.elapsed();
        Ok(ClientProbeMeasurement {
            transferred_bytes,
            duration: latency,
            latency,
        })
    }

    async fn read_response_body(
        &self,
        response: Response,
        max_bytes: usize,
        cancel: &CancellationToken,
    ) -> Result<Vec<u8>, ClientProbeError> {
        let max_bytes_u64 = u64::try_from(max_bytes).map_err(|_| ClientProbeError::ProtocolFailure)?;
        if response.content_length().is_some_and(|length| length > max_bytes_u64) {
            return Err(ClientProbeError::ProtocolFailure);
        }
        let mut body = Vec::with_capacity(max_bytes.min(MAX_CLIENT_RESPONSE_BYTES));
        let mut stream = response.bytes_stream();
        loop {
            let chunk = tokio::select! {
                () = cancel.cancelled() => return Err(ClientProbeError::Cancelled),
                chunk = stream.next() => chunk,
            };
            let Some(chunk) = chunk else {
                break;
            };
            let chunk = chunk.map_err(|error| self.transport_error(&error))?;
            let new_length = body.len().checked_add(chunk.len()).ok_or(ClientProbeError::ProtocolFailure)?;
            if new_length > max_bytes {
                return Err(ClientProbeError::ProtocolFailure);
            }
            body.extend_from_slice(&chunk);
        }
        Ok(body)
    }

    fn transport_error(&self, error: &reqwest::Error) -> ClientProbeError {
        if error.is_timeout() {
            ClientProbeError::TimedOut
        } else if self.proxy_configured {
            ClientProbeError::ProxyFailure
        } else if error.is_connect() {
            ClientProbeError::EndpointUnavailable
        } else {
            ClientProbeError::ProtocolFailure
        }
    }
}

impl ClientProbe for HttpClientProbe {
    fn probe<'a>(&'a self, request: &'a ClientPerformanceRequest, cancel: &'a CancellationToken) -> ClientProbeFuture<'a> {
        Box::pin(self.execute(request, cancel))
    }
}

#[derive(Deserialize)]
struct ClientDevnullResponse {
    kind: String,
    measured: bool,
    rx_bytes: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SignedClientExport {
    pub artifact_uid: String,
    pub outcome: ClientOutcome,
    pub reason_code: ClientReasonCode,
    pub envelope_json: Vec<u8>,
    pub envelope_signature: Vec<u8>,
    pub result_json: Vec<u8>,
    pub archive_bytes: Vec<u8>,
    pub archive_sha256: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SavedClientExport {
    pub artifact_uid: String,
    pub archive_size_bytes: u64,
    pub archive_sha256: String,
}

#[derive(Debug, Error)]
pub enum ClientPerformanceError {
    #[error("client_performance_local_consent_required")]
    ConsentRequired,
    #[error("client_performance_local_consent_expired")]
    ConsentExpired,
    #[error("client_performance_request_expired")]
    Expired,
    #[error("client_performance_invalid_request")]
    InvalidRequest,
    #[error("client_performance_unsupported_version")]
    UnsupportedVersion,
    #[error("client_performance_unsupported_capability")]
    UnsupportedCapability,
    #[error("client_performance_limit_exceeded")]
    LimitExceeded,
    #[error("client_performance_collection_cancelled")]
    Cancelled,
    #[error("client_performance_busy")]
    Busy,
    #[error("client_performance_invalid_endpoint")]
    InvalidEndpoint,
    #[error("client_performance_invalid_proxy")]
    InvalidProxy,
    #[error("client_performance_invalid_root_certificate")]
    InvalidRootCertificate,
    #[error("client_performance_invalid_credential")]
    InvalidCredential,
    #[error("client_performance_transport_configuration")]
    TransportConfiguration,
    #[error("client_performance_signing_failed")]
    Signing,
    #[error("client_performance_encoding_failed")]
    Encoding,
    #[error("client_performance_output_exists")]
    AlreadyExists,
    #[error("client_performance_io_failed")]
    Io(#[source] std::io::Error),
    #[error("client_performance_output_durability_failed")]
    DurabilityAfterCommit(#[source] std::io::Error),
}

pub async fn measure_client(
    request: &ClientPerformanceRequest,
    probe: &impl ClientProbe,
    cancel: &CancellationToken,
) -> Result<ClientMeasurement, ClientPerformanceError> {
    request.validate(unix_now()?)?;
    if CLIENT_COLLECTOR_ACTIVE
        .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        return Err(ClientPerformanceError::Busy);
    }
    let _guard = ActiveGuard;
    if cancel.is_cancelled() {
        return Ok(terminal_measurement(
            request,
            ClientOutcome::Cancelled,
            ClientReasonCode::Cancelled,
            ClientTargetReasonCode::Cancelled,
            Duration::ZERO,
        ));
    }
    let started = Instant::now();
    let deadline = tokio::time::sleep(request.duration);
    tokio::pin!(deadline);
    let probe = probe.probe(request, cancel);
    tokio::pin!(probe);
    let result = tokio::select! {
        () = cancel.cancelled() => Err(ClientProbeError::Cancelled),
        () = &mut deadline => Err(ClientProbeError::TimedOut),
        result = &mut probe => result,
    };
    Ok(match result {
        Ok(sample) if sample.transferred_bytes == request.traffic_bytes => success_measurement(request, sample),
        Ok(_) => failed_measurement(request, started.elapsed(), ClientTargetReasonCode::ProtocolFailure),
        Err(ClientProbeError::Cancelled) => terminal_measurement(
            request,
            ClientOutcome::Cancelled,
            ClientReasonCode::Cancelled,
            ClientTargetReasonCode::Cancelled,
            started.elapsed(),
        ),
        Err(error) => failed_measurement(request, started.elapsed(), target_reason(error)),
    })
}

pub fn sign_client_export(
    request: &ClientPerformanceRequest,
    measurement: &ClientMeasurement,
    key: &DeviceIdentity,
    cancel: &CancellationToken,
) -> Result<SignedClientExport, ClientPerformanceError> {
    request.validate(unix_now()?)?;
    check_cancel(cancel)?;
    let result = &measurement.result;
    if result.outcome != ClientOutcome::Succeeded
        || result.data.is_none()
        || result.run_uid != request.run_uid
        || result.schema_version != CLIENT_SCHEMA_VERSION
        || result.tool_id != CLIENT_TOOL_ID
        || result.capability != CLIENT_CAPABILITY
    {
        return Err(ClientPerformanceError::InvalidRequest);
    }
    let result_json = serde_json::to_vec(result).map_err(|_| ClientPerformanceError::Encoding)?;
    if result_json.is_empty() || result_json.len() > MAX_CLIENT_RESULT_BYTES {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    let device_key_id = hex_lower(&Sha256::digest(key.public_key_der()));
    let result_sha256 = hex_lower(&Sha256::digest(&result_json));
    let envelope = ClientEnvelope {
        format_version: "rustfs.connect.diagnosticEnvelope/1",
        protocol_version: "v1",
        organization_name: &request.organization_name,
        cluster_name: &request.cluster_name,
        device_name: &request.device_name,
        run_uid: &request.run_uid,
        artifact_uid: &request.artifact_uid,
        tool_id: CLIENT_TOOL_ID,
        schema_version: CLIENT_SCHEMA_VERSION,
        classification: "L1",
        consent_uid: &request.consent.consent_uid,
        policy_revision: request.consent.policy_revision,
        produced_at: timestamp(request.produced_at_unix)?,
        expires_at: timestamp(request.expires_at_unix)?,
        nonce: URL_SAFE_NO_PAD.encode_to_string(request.nonce),
        device_key_id: &device_key_id,
        payload: ClientPayload {
            path: RESULT_PATH,
            media_type: "application/json",
            size_bytes: u64::try_from(result_json.len()).map_err(|_| ClientPerformanceError::LimitExceeded)?,
            sha256: &result_sha256,
        },
    };
    let envelope_json = serde_json::to_vec(&envelope).map_err(|_| ClientPerformanceError::Encoding)?;
    if envelope_json.is_empty() || envelope_json.len() > MAX_ENVELOPE_BYTES {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    let envelope_signature = signature_document(key, &device_key_id, &envelope_json)?;
    let decompressed = result_json
        .len()
        .checked_add(envelope_json.len())
        .and_then(|size| size.checked_add(envelope_signature.len()))
        .ok_or(ClientPerformanceError::LimitExceeded)?;
    if decompressed > MAX_DECOMPRESSED_BYTES {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    check_cancel(cancel)?;
    if unix_now()? >= request.expires_at_unix {
        return Err(ClientPerformanceError::Expired);
    }
    let archive_bytes = archive(&envelope_json, &envelope_signature, &result_json)?;
    if archive_bytes.len() > MAX_ARCHIVE_BYTES {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    let archive_sha256 = hex_lower(&Sha256::digest(&archive_bytes));
    Ok(SignedClientExport {
        artifact_uid: request.artifact_uid.clone(),
        outcome: result.outcome,
        reason_code: result.reason_code,
        envelope_json,
        envelope_signature,
        result_json,
        archive_bytes,
        archive_sha256,
    })
}

pub fn save_signed_client_export(
    output: &Path,
    export: &SignedClientExport,
    cancel: &CancellationToken,
) -> Result<SavedClientExport, ClientPerformanceError> {
    check_cancel(cancel)?;
    if !uuid7(&export.artifact_uid) || export.archive_bytes.is_empty() {
        return Err(ClientPerformanceError::InvalidRequest);
    }
    if export.archive_bytes.len() > MAX_ARCHIVE_BYTES {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    if hex_lower(&Sha256::digest(&export.archive_bytes)) != export.archive_sha256 {
        return Err(ClientPerformanceError::InvalidRequest);
    }
    let parent = output
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let filename = output
        .file_name()
        .ok_or(ClientPerformanceError::InvalidRequest)?
        .to_string_lossy();
    let temporary = parent.join(format!(".{filename}.{}.partial", export.artifact_uid));
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        options.mode(OUTPUT_MODE);
    }
    let mut file = options.open(&temporary).map_err(map_create_error)?;
    let saved = (|| {
        file.write_all(&export.archive_bytes).map_err(ClientPerformanceError::Io)?;
        check_cancel(cancel)?;
        file.sync_all().map_err(ClientPerformanceError::Io)?;
        check_cancel(cancel)?;
        fs::hard_link(&temporary, output).map_err(map_publish_error)?;
        fs::remove_file(&temporary).map_err(ClientPerformanceError::DurabilityAfterCommit)?;
        #[cfg(unix)]
        File::open(parent)
            .and_then(|directory| directory.sync_all())
            .map_err(ClientPerformanceError::DurabilityAfterCommit)?;
        Ok(SavedClientExport {
            artifact_uid: export.artifact_uid.clone(),
            archive_size_bytes: u64::try_from(export.archive_bytes.len()).map_err(|_| ClientPerformanceError::LimitExceeded)?,
            archive_sha256: export.archive_sha256.clone(),
        })
    })();
    if saved.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    saved
}

pub fn validate_client_limits(duration: Duration, traffic_bytes: u64) -> Result<(), ClientPerformanceError> {
    if duration.is_zero()
        || duration.as_millis() == 0
        || duration > MAX_CLIENT_DURATION
        || traffic_bytes == 0
        || traffic_bytes > MAX_CLIENT_TRAFFIC_BYTES
    {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    let bandwidth_budget = u64::try_from(
        u128::from(MAX_CLIENT_BANDWIDTH_BYTES_PER_SECOND)
            .checked_mul(duration.as_millis())
            .ok_or(ClientPerformanceError::LimitExceeded)?
            / 1_000,
    )
    .map_err(|_| ClientPerformanceError::LimitExceeded)?;
    if traffic_bytes > bandwidth_budget.max(1) {
        return Err(ClientPerformanceError::LimitExceeded);
    }
    Ok(())
}

pub fn read_protected_client_credential(path: &Path) -> Result<Zeroizing<String>, ClientPerformanceError> {
    let metadata = fs::symlink_metadata(path).map_err(ClientPerformanceError::Io)?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(ClientPerformanceError::InvalidCredential);
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt as _, OpenOptionsExt as _, PermissionsExt as _};
        if metadata.uid() != process_uid() || metadata.permissions().mode() & 0o077 != 0 {
            return Err(ClientPerformanceError::InvalidCredential);
        }
        let mut options = OpenOptions::new();
        options.read(true).custom_flags(libc::O_CLOEXEC | libc::O_NOFOLLOW);
        let mut file = options.open(path).map_err(ClientPerformanceError::Io)?;
        let opened = file.metadata().map_err(ClientPerformanceError::Io)?;
        if opened.dev() != metadata.dev() || opened.ino() != metadata.ino() {
            return Err(ClientPerformanceError::InvalidCredential);
        }
        read_credential_value(&mut file)
    }
    #[cfg(not(unix))]
    {
        let mut file = File::open(path).map_err(ClientPerformanceError::Io)?;
        read_credential_value(&mut file)
    }
}

fn read_credential_value(reader: &mut impl Read) -> Result<Zeroizing<String>, ClientPerformanceError> {
    let mut bytes = Vec::with_capacity(256);
    reader
        .take(4_097)
        .read_to_end(&mut bytes)
        .map_err(ClientPerformanceError::Io)?;
    if bytes.is_empty() || bytes.len() > 4_096 || bytes.contains(&0) {
        return Err(ClientPerformanceError::InvalidCredential);
    }
    while matches!(bytes.last(), Some(b'\n' | b'\r')) {
        bytes.pop();
    }
    let value = String::from_utf8(bytes).map_err(|_| ClientPerformanceError::InvalidCredential)?;
    if value.is_empty() || value.len() > 4_096 || value.trim() != value {
        return Err(ClientPerformanceError::InvalidCredential);
    }
    Ok(Zeroizing::new(value))
}

#[cfg(unix)]
#[allow(unsafe_code)]
fn process_uid() -> u32 {
    // SAFETY: geteuid has no pointer arguments or caller preconditions.
    unsafe { libc::geteuid() }
}

impl ClientPerformanceRequest {
    fn validate(&self, now_unix: i64) -> Result<(), ClientPerformanceError> {
        if self.schema_version != CLIENT_SCHEMA_VERSION {
            return Err(ClientPerformanceError::UnsupportedVersion);
        }
        if self.capability != CLIENT_CAPABILITY {
            return Err(ClientPerformanceError::UnsupportedCapability);
        }
        if !self.consent.confirmed || self.consent.policy_revision == 0 {
            return Err(ClientPerformanceError::ConsentRequired);
        }
        if self.consent.expires_at_unix <= now_unix || self.expires_at_unix > self.consent.expires_at_unix {
            return Err(ClientPerformanceError::ConsentExpired);
        }
        let validity = self
            .expires_at_unix
            .checked_sub(self.produced_at_unix)
            .ok_or(ClientPerformanceError::Expired)?;
        if self.produced_at_unix > now_unix.saturating_add(MAX_FUTURE_SKEW_SECONDS)
            || validity <= 0
            || validity > MAX_VALIDITY_SECONDS
            || self.expires_at_unix <= now_unix
        {
            return Err(ClientPerformanceError::Expired);
        }
        validate_client_limits(self.duration, self.traffic_bytes)?;
        if !uuid7(&self.run_uid)
            || !uuid7(&self.artifact_uid)
            || !uuid7(&self.consent.consent_uid)
            || !resource_names_match(self)
            || self.target_alias.is_empty()
            || self.target_alias.len() > 128
            || !self
                .target_alias
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || b"._:-".contains(&byte))
            || !lower_hex_string(&self.provenance.source_commit, 40)
            || !lower_hex_string(&self.provenance.executable_sha256, 64)
            || !version(&self.provenance.rustfs_version)
            || self.provenance.build_features.len() > MAX_BUILD_FEATURES
            || !self.provenance.build_features.iter().all(|value| build_feature(value))
        {
            return Err(ClientPerformanceError::InvalidRequest);
        }
        Ok(())
    }
}

struct ActiveGuard;

impl Drop for ActiveGuard {
    fn drop(&mut self) {
        CLIENT_COLLECTOR_ACTIVE.store(false, Ordering::Release);
    }
}

fn success_measurement(request: &ClientPerformanceRequest, sample: ClientProbeMeasurement) -> ClientMeasurement {
    let duration_millis = elapsed_millis(sample.duration);
    let data = ClientPerformanceData {
        operation: request.operation,
        transferred_bytes: sample.transferred_bytes,
        completed_operations: 1,
        duration_millis,
        error_count: 0,
    };
    ClientMeasurement {
        result: result(
            request,
            ClientOutcome::Succeeded,
            ClientReasonCode::Complete,
            duration_millis,
            1,
            Some(data),
        ),
        target: ClientTargetResult {
            target_alias: request.target_alias.clone(),
            outcome: ClientOutcome::Succeeded,
            reason_code: ClientTargetReasonCode::Complete,
            parameters: target_parameters(request),
            units: target_units(),
            transferred_bytes: sample.transferred_bytes,
            completed_operations: 1,
            latency_micros: Some(elapsed_micros(sample.latency)),
            duration_millis,
        },
    }
}

fn failed_measurement(
    request: &ClientPerformanceRequest,
    elapsed: Duration,
    target_reason: ClientTargetReasonCode,
) -> ClientMeasurement {
    let reason = match target_reason {
        ClientTargetReasonCode::EndpointUnavailable => ClientReasonCode::SourceUnavailable,
        ClientTargetReasonCode::PermissionDenied => ClientReasonCode::PermissionDenied,
        _ => ClientReasonCode::CollectionFailed,
    };
    terminal_measurement(request, ClientOutcome::Failed, reason, target_reason, elapsed)
}

fn terminal_measurement(
    request: &ClientPerformanceRequest,
    outcome: ClientOutcome,
    reason_code: ClientReasonCode,
    target_reason: ClientTargetReasonCode,
    elapsed: Duration,
) -> ClientMeasurement {
    let duration_millis = elapsed_millis_allow_zero(elapsed);
    ClientMeasurement {
        result: result(request, outcome, reason_code, duration_millis, 0, None),
        target: ClientTargetResult {
            target_alias: request.target_alias.clone(),
            outcome,
            reason_code: target_reason,
            parameters: target_parameters(request),
            units: target_units(),
            transferred_bytes: 0,
            completed_operations: 0,
            latency_micros: None,
            duration_millis,
        },
    }
}

fn target_reason(error: ClientProbeError) -> ClientTargetReasonCode {
    match error {
        ClientProbeError::EndpointUnavailable => ClientTargetReasonCode::EndpointUnavailable,
        ClientProbeError::ProxyFailure => ClientTargetReasonCode::ProxyFailure,
        ClientProbeError::PermissionDenied => ClientTargetReasonCode::PermissionDenied,
        ClientProbeError::TimedOut => ClientTargetReasonCode::TimedOut,
        ClientProbeError::Cancelled => ClientTargetReasonCode::Cancelled,
        ClientProbeError::ProtocolFailure => ClientTargetReasonCode::ProtocolFailure,
    }
}

fn target_parameters(request: &ClientPerformanceRequest) -> ClientTargetParameters {
    ClientTargetParameters {
        operation: request.operation,
        requested_bytes: request.traffic_bytes,
        duration_millis: elapsed_millis_allow_zero(request.duration),
        concurrency: 1,
    }
}

fn target_units() -> ClientTargetUnits {
    ClientTargetUnits {
        bytes: "BYTE",
        duration: "MILLISECOND",
        latency: "MICROSECOND",
        operation_count: "OPERATION",
    }
}

fn result(
    request: &ClientPerformanceRequest,
    outcome: ClientOutcome,
    reason_code: ClientReasonCode,
    duration_millis: u64,
    completed_units: u32,
    data: Option<ClientPerformanceData>,
) -> ClientDiagnosticResult {
    ClientDiagnosticResult {
        schema_version: CLIENT_SCHEMA_VERSION,
        run_uid: request.run_uid.clone(),
        tool_id: CLIENT_TOOL_ID,
        capability: CLIENT_CAPABILITY,
        outcome,
        reason_code,
        duration_millis: duration_millis.min(30_000),
        provenance: request.provenance.clone(),
        coverage: ClientCoverage {
            requested_units: 1,
            completed_units,
            unit: "WINDOW",
        },
        data,
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ClientEnvelope<'a> {
    format_version: &'static str,
    protocol_version: &'static str,
    organization_name: &'a str,
    cluster_name: &'a str,
    device_name: &'a str,
    run_uid: &'a str,
    artifact_uid: &'a str,
    tool_id: &'static str,
    schema_version: u16,
    classification: &'static str,
    consent_uid: &'a str,
    policy_revision: u64,
    produced_at: String,
    expires_at: String,
    nonce: String,
    device_key_id: &'a str,
    payload: ClientPayload<'a>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ClientPayload<'a> {
    path: &'static str,
    media_type: &'static str,
    size_bytes: u64,
    sha256: &'a str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ClientSignature<'a> {
    algorithm: &'static str,
    key_id: &'a str,
    value: String,
}

fn signature_document(key: &DeviceIdentity, key_id: &str, envelope: &[u8]) -> Result<Vec<u8>, ClientPerformanceError> {
    let pkcs8 = key.to_pkcs8_der().map_err(|_| ClientPerformanceError::Signing)?;
    let signing_key = SigningKey::from_pkcs8_der(pkcs8.as_slice()).map_err(|_| ClientPerformanceError::Signing)?;
    let mut input = Vec::with_capacity(SIGNATURE_DOMAIN.len() + envelope.len());
    input.extend_from_slice(SIGNATURE_DOMAIN);
    input.extend_from_slice(envelope);
    let signature: Signature = signing_key.sign(&input);
    serde_json::to_vec(&ClientSignature {
        algorithm: "ES256",
        key_id,
        value: URL_SAFE_NO_PAD.encode_to_string(signature.normalize_s().to_bytes()),
    })
    .map_err(|_| ClientPerformanceError::Encoding)
}

fn archive(envelope: &[u8], signature: &[u8], result: &[u8]) -> Result<Vec<u8>, ClientPerformanceError> {
    let cursor = Cursor::new(Vec::with_capacity(envelope.len() + signature.len() + result.len() + 512));
    let mut writer = ZipWriter::new(cursor);
    let options = SimpleFileOptions::DEFAULT
        .compression_method(CompressionMethod::Stored)
        .unix_permissions(OUTPUT_MODE);
    for (name, bytes) in [(ENVELOPE_PATH, envelope), (SIGNATURE_PATH, signature), (RESULT_PATH, result)] {
        writer
            .start_file(name, options)
            .map_err(|_| ClientPerformanceError::Encoding)?;
        writer.write_all(bytes).map_err(ClientPerformanceError::Io)?;
    }
    writer
        .finish()
        .map(|cursor| cursor.into_inner())
        .map_err(|_| ClientPerformanceError::Encoding)
}

fn deployment_endpoint(value: &str) -> Result<Url, ClientPerformanceError> {
    let mut url = Url::parse(value).map_err(|_| ClientPerformanceError::InvalidEndpoint)?;
    let local_http = url.scheme() == "http"
        && url
            .host_str()
            .is_some_and(|host| host == "localhost" || host.parse::<std::net::IpAddr>().is_ok_and(|ip| ip.is_loopback()));
    if (url.scheme() != "https" && !local_http)
        || url.cannot_be_a_base()
        || !url.username().is_empty()
        || url.password().is_some()
        || url.query().is_some()
        || url.fragment().is_some()
    {
        return Err(ClientPerformanceError::InvalidEndpoint);
    }
    url.set_query(None);
    url.set_fragment(None);
    if !url.path().ends_with('/') {
        url.set_path(&format!("{}/", url.path()));
    }
    Ok(url)
}

fn proxy_url(value: &str) -> Result<Url, ClientPerformanceError> {
    let url = Url::parse(value).map_err(|_| ClientPerformanceError::InvalidProxy)?;
    if !matches!(url.scheme(), "http" | "https")
        || url.cannot_be_a_base()
        || !url.username().is_empty()
        || url.password().is_some()
        || url.query().is_some()
        || url.fragment().is_some()
    {
        return Err(ClientPerformanceError::InvalidProxy);
    }
    Ok(url)
}

fn resource_names_match(request: &ClientPerformanceRequest) -> bool {
    let Some(organization_uid) = request.organization_name.strip_prefix("organizations/") else {
        return false;
    };
    if !uuid7(organization_uid) {
        return false;
    }
    let cluster_prefix = format!("{}/clusters/", request.organization_name);
    let Some(cluster_uid) = request.cluster_name.strip_prefix(&cluster_prefix) else {
        return false;
    };
    if !uuid7(cluster_uid) {
        return false;
    }
    let device_prefix = format!("{}/clusterDevices/", request.cluster_name);
    request.device_name.strip_prefix(&device_prefix).is_some_and(uuid7)
}

fn uuid7(value: &str) -> bool {
    Uuid::parse_str(value).is_ok_and(|uuid| {
        uuid.get_version() == Some(Version::SortRand) && uuid.get_variant() == Variant::RFC4122 && uuid.to_string() == value
    })
}

fn lower_hex_string(value: &str, length: usize) -> bool {
    value.len() == length
        && value
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
}

fn version(value: &str) -> bool {
    if value.is_empty() || value.len() > 64 {
        return false;
    }
    let (core, prerelease) = value
        .split_once('-')
        .map_or((value, None), |(core, prerelease)| (core, Some(prerelease)));
    let mut parts = core.split('.');
    let valid_core = (0..3).all(|_| {
        parts
            .next()
            .is_some_and(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
    }) && parts.next().is_none();
    valid_core
        && prerelease.is_none_or(|part| {
            !part.is_empty()
                && part
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-'))
        })
}

fn build_feature(value: &str) -> bool {
    value.len() <= 64
        && value.as_bytes().split_first().is_some_and(|(first, rest)| {
            first.is_ascii_lowercase()
                && rest
                    .iter()
                    .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_'))
        })
}

fn elapsed_millis(duration: Duration) -> u64 {
    elapsed_millis_allow_zero(duration).max(1)
}

fn elapsed_millis_allow_zero(duration: Duration) -> u64 {
    u64::try_from(duration.as_millis()).unwrap_or(u64::MAX).min(MAX_SAFE_INTEGER)
}

fn elapsed_micros(duration: Duration) -> u64 {
    u64::try_from(duration.as_micros()).unwrap_or(u64::MAX).min(MAX_SAFE_INTEGER)
}

fn unix_now() -> Result<i64, ClientPerformanceError> {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| ClientPerformanceError::InvalidRequest)
        .and_then(|duration| i64::try_from(duration.as_secs()).map_err(|_| ClientPerformanceError::InvalidRequest))
}

fn timestamp(unix: i64) -> Result<String, ClientPerformanceError> {
    OffsetDateTime::from_unix_timestamp(unix)
        .map_err(|_| ClientPerformanceError::InvalidRequest)?
        .format(&Rfc3339)
        .map_err(|_| ClientPerformanceError::Encoding)
}

fn check_cancel(cancel: &CancellationToken) -> Result<(), ClientPerformanceError> {
    if cancel.is_cancelled() {
        Err(ClientPerformanceError::Cancelled)
    } else {
        Ok(())
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        use std::fmt::Write as _;
        let _ = write!(encoded, "{byte:02x}");
    }
    encoded
}

fn map_create_error(error: std::io::Error) -> ClientPerformanceError {
    if error.kind() == std::io::ErrorKind::AlreadyExists {
        ClientPerformanceError::AlreadyExists
    } else {
        ClientPerformanceError::Io(error)
    }
}

fn map_publish_error(error: std::io::Error) -> ClientPerformanceError {
    if error.kind() == std::io::ErrorKind::AlreadyExists {
        ClientPerformanceError::AlreadyExists
    } else {
        ClientPerformanceError::Io(error)
    }
}
