// Copyright 2024 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Generates the `S3ErrorCode` enum from `src/codes.txt`.
//!
//! Responsible for: turning the byte-sorted name list into the enum, its
//! `NAMED` table, `as_str`, and the exact and lowercase name lookups.
//! Not responsible for: HTTP statuses, parsing policy, or `Display`; those are
//! hand-written in `src/error/code.rs` against the generated enum.
//! Upstream: `src/codes.txt`. Downstream: `src/error/code.rs` includes the output.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const CODES: &str = "src/codes.txt";
const OUTPUT: &str = "s3_error_code.rs";

fn main() {
    println!("cargo:rerun-if-changed={CODES}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR for build scripts");
    let out_dir = env::var("OUT_DIR").expect("cargo always sets OUT_DIR for build scripts");

    let text = fs::read_to_string(Path::new(&manifest_dir).join(CODES))
        .unwrap_or_else(|error| panic!("{CODES}: cannot read the code list: {error}"));
    let names = parse_names(&text).unwrap_or_else(|error| panic!("{CODES}: {error}"));
    let generated = render(&names);
    fs::write(Path::new(&out_dir).join(OUTPUT), generated)
        .unwrap_or_else(|error| panic!("{OUTPUT}: cannot write the generated enum: {error}"));
}

/// Reads the named variants: one identifier per line, `#` comments and blank
/// lines skipped, byte-sorted and unique, with `Custom` present exactly once
/// and excluded from the result because it is emitted as a tuple variant.
fn parse_names(text: &str) -> Result<Vec<&str>, String> {
    let mut names: Vec<&str> = Vec::new();
    let mut lowercase = std::collections::HashSet::new();
    let mut custom_lines = 0usize;
    for (index, raw) in text.lines().enumerate() {
        let line_no = index + 1;
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line != raw {
            return Err(format!("line {line_no}: surrounding whitespace is not allowed"));
        }
        if !is_variant_name(line) {
            return Err(format!("line {line_no}: {line:?} is not an UpperCamelCase ASCII identifier"));
        }
        if line == "Custom" {
            custom_lines += 1;
            continue;
        }
        if let Some(previous) = names.last()
            && *previous >= line
        {
            return Err(format!(
                "line {line_no}: {line:?} must come after {previous:?}; the list is byte-sorted and unique, regenerate it with the command in the header"
            ));
        }
        if !lowercase.insert(line.to_ascii_lowercase()) {
            return Err(format!("line {line_no}: {line:?} collides with another name ignoring ASCII case"));
        }
        names.push(line);
    }
    if custom_lines != 1 {
        return Err(format!("`Custom` must be listed exactly once, found {custom_lines} lines"));
    }
    if names.is_empty() {
        return Err("no named variants found".to_owned());
    }
    Ok(names)
}

fn is_variant_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars.next().is_some_and(|first| first.is_ascii_uppercase()) && chars.all(|c| c.is_ascii_alphanumeric())
}

fn render(names: &[&str]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by build.rs from src/codes.txt. Do not edit.\n\n");
    out.push_str("/// Error codes raised by RustFS, named exactly as they appear on the wire.\n");
    out.push_str("///\n");
    out.push_str("/// The named set is derived from RustFS's own call surface (`src/codes.txt`);\n");
    out.push_str("/// anything outside it travels as [`S3ErrorCode::Custom`].\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum S3ErrorCode {\n");
    for name in names {
        let _ = writeln!(out, "    {name},");
    }
    out.push_str("    /// A code outside the named set, carried verbatim.\n");
    out.push_str("    Custom(::std::borrow::Cow<'static, str>),\n");
    out.push_str("}\n\n");

    out.push_str("impl S3ErrorCode {\n");
    out.push_str("    /// Every named variant in `src/codes.txt` order; `Custom` is not a member.\n");
    out.push_str("    pub const NAMED: &'static [S3ErrorCode] = &[\n");
    for name in names {
        let _ = writeln!(out, "        S3ErrorCode::{name},");
    }
    out.push_str("    ];\n\n");

    out.push_str("    /// The wire name of the code; a `Custom` code yields its own text.\n");
    out.push_str("    pub fn as_str(&self) -> &str {\n");
    out.push_str("        match self {\n");
    for name in names {
        let _ = writeln!(out, "            Self::{name} => {name:?},");
    }
    out.push_str("            Self::Custom(code) => code,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    fn named_from_exact(name: &str) -> Option<Self> {\n");
    out.push_str("        match name {\n");
    for name in names {
        let _ = writeln!(out, "            {name:?} => Some(Self::{name}),");
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    fn named_from_lowercase(lowercase: &str) -> Option<Self> {\n");
    out.push_str("        match lowercase {\n");
    for name in names {
        let lower = name.to_ascii_lowercase();
        let _ = writeln!(out, "            {lower:?} => Some(Self::{name}),");
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}
