name: mint-test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  mintest:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: install protoc
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v27.0/protoc-27.0-linux-x86_64.zip
          unzip protoc-27.0-linux-x86_64.zip -d protoc3
          mv protoc3/bin/* /usr/local/bin/
          chmod +x /usr/local/bin/protoc
          rm -rf protoc-27.0-linux-x86_64.zip protoc3
  
      - name: install flatc
        run: |
          wget https://github.com/google/flatbuffers/releases/download/v24.3.25/Linux.flatc.binary.g++-13.zip
          unzip Linux.flatc.binary.g++-13.zip
          mv flatc /usr/local/bin/ 
          chmod +x /usr/local/bin/flatc 
          rm -rf Linux.flatc.binary.g++-13.zip
  
      - name: checkout source code
        uses: actions/checkout@v4
  
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
  
      - name: cargo build & release
        run: cargo build --release

      - name: run this rustfs server
        run: |
          mkdir -p data/rustfs
          nohup ./target/release/rustfs \
            --address 0.0.0.0:9000 \
            --access-key rustfsadmin \
            --secret-key rustfsadmin \
            --domain-name localhost:9000 \
            data/rustfs &

      - name: run mint test task
        run: |
          ps aux | grep rustfs
          docker run -e SERVER_ENDPOINT=localhost:9000 \
            -e ACCESS_KEY=rustfsadmin \
            -e SECRET_KEY=rustfsadmin \
            -e ENABLE_HTTPS=1 \
            minio/mint
  
